### ISSUE TITLE
Node 0.10 support is broken

### ISSUE THREAD

**Issue by dominicbarnes** [duojs/package#54]
Should we continue supporting `0.10`? Or is it time to move onto `0.12` and iojs?

**Comment by stephenmathieson** [comment]
it'd be nice to remove all of the gnode stuff, so i'm inclined to drop 0.10 support.  i've either been using 0.11 or iojs for quite awhile now..

**BUT** for work stuff, i'm stuck on node 0.10 for awhile... :/

**Comment by stephenmathieson** [comment]
we dropped node 10 support, right?

**Comment by dominicbarnes** [comment]
Yeah, we've dropped supporting it in core, although we are still running tests for node 0.10 using gnode.
